version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22

    commands:
      # install npm
      - npm install
      - npm install --save-dev @babel/plugin-proposal-private-property-in-object
  build:
    commands:
      # run build script
      - npm run build

  post_build:
    commands:
      #- aws s3 cp s3://codepipeline-us-east-1-908788960299/Dev-Pipeline-Finprom/
      #the command below works, but i don't need to get the build file from S3 bucket, it's the build folder o
      #of the project
      #- sudo aws s3 cp s3://codepipeline-us-east-1-908788960299/Dev-Pipeline-Finprom/build/ /var/www/html --recursive

      #s3://fpfrontends3/178eec96-791b-49e5-b13c-4b734e44362d.gz
      # - sudo scp -r build/* /var/www/html
      #- aws s3 cp s3://codepipeline-us-east-2-992243525314/fpt-Pipeline/BuildArtif/ /var/www/vhosts/frontend --recursive
      #**
      - aws s3 cp --recursive ./build/ s3://codepipeline-us-east-2-992243525314/fpt-Pipeline/BuildArtif/build/
      #- aws s3 cp --recursive s3://codepipeline-us-east-2-992243525314/fpt-Pipeline/BuildArtif/build/ /fp-dashboard-dev/
      #s- aws s3 cp --recursive ./build/ /fp-dashboard-dev/
      #build/ /fp-dashboard-dev --recursive

      - sudo scp -r ./build/ /var/www/vhosts/frontend/

artifacts:
  # include all files required to run application
  # notably excluded is node_modules, as this will cause overwrite error on deploy
  files:
    - public/**/*
    - src/**/*
    - package.json
    - appspec.yml
    - scripts/**/*
    - build/**/*
cache:
  paths:
    - "node_modules/**/*"
# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       nodejs: 18

#     commands:
#       # install npm
#       - npm install

#   build:
#     commands:
#       # run build script
#       - npm run build

#   post_build:
#     command:
#     aws s3 cps3://fpfrontends3/178eec96-791b-49e5-b13c-4b734e44362d.gz
#       #- sudo scp -r build/* /var/www/html
# artifacts:
#   # include all files required to run application
#   # notably excluded is node_modules, as this will cause overwrite error on deploy
#   files:
#     - public/**/*
#     - src/**/*
#     - package.json
#     - appspec.yml
#     - buildspec.yml
#     - scripts/**/*

